(namespace EntryPoint)

(function Main -> (Int32 result):		
   (result = 12)
	(		
			try ( (Double 11 -> result) )   
			catch e ( result = (result + 15) )
   )
)	
		
(function Double (Int32 x) -> (Int32 y):		
   (Int32 z)
   (Sys.Type.IException ex (EntryPoint.NewException))(throw ex)			
   (y = (2 * x))
)
			
(method TestException.ErrorCode -> (Int32 errorCode): 
	(errorCode = 0)
)

(method TestException.Message -> (Sys.Type.IString s):
	(s = "This is to be expected")
)
 
(method TestException.Construct : )

(class TestException (implements Sys.Type.IException))

(factory EntryPoint.NewException Sys.Type.IException :
	(construct TestException)
)

(alias Main EntryPoint.Main)
